// Code generated by "genprotocol -ver=ee0c2a9542c23df14c7723030f3c8ad53da871d9e014d150b2e62d1ce8399fde -basedir=. -prefix=gos -statstype=int"

package gos_connbytemanager

import (
	"fmt"
	"sync"

	"github.com/kasworld/goonlinescaffolding/protocol_gos/gos_serveconnbyte"
)

type Manager struct {
	mutex   sync.RWMutex
	id2Conn map[string]*gos_serveconnbyte.ServeConnByte
}

func New() *Manager {
	rtn := &Manager{
		id2Conn: make(map[string]*gos_serveconnbyte.ServeConnByte),
	}
	return rtn
}
func (cm *Manager) Add(id string, c2sc *gos_serveconnbyte.ServeConnByte) error {
	cm.mutex.Lock()
	defer cm.mutex.Unlock()
	if cm.id2Conn[id] != nil {
		return fmt.Errorf("already exist %v", id)
	}
	cm.id2Conn[id] = c2sc
	return nil
}
func (cm *Manager) Del(id string) error {
	cm.mutex.Lock()
	defer cm.mutex.Unlock()
	if cm.id2Conn[id] == nil {
		return fmt.Errorf("not exist %v", id)
	}
	delete(cm.id2Conn, id)
	return nil
}
func (cm *Manager) Get(id string) *gos_serveconnbyte.ServeConnByte {
	cm.mutex.RLock()
	defer cm.mutex.RUnlock()
	return cm.id2Conn[id]
}
func (cm *Manager) Len() int {
	return len(cm.id2Conn)
}
func (cm *Manager) GetList() []*gos_serveconnbyte.ServeConnByte {
	rtn := make([]*gos_serveconnbyte.ServeConnByte, 0, len(cm.id2Conn))
	cm.mutex.RLock()
	defer cm.mutex.RUnlock()
	for _, v := range cm.id2Conn {
		rtn = append(rtn, v)
	}
	return rtn
}
