// Code generated by "genprotocol -ver=68269c8bfeecd6e461aa862d64007f60a1aeccd64229d523ae7b99a446255112 -basedir=. -prefix=gos -statstype=int"

package gos_handlersp

/* obj base demux fn map template

var DemuxRsp2ObjFnMap = [...]func(me interface{}, hd gos_packet.Header, body interface{}) error {
gos_idcmd.Invalid : objRecvRspFn_Invalid,
gos_idcmd.Login : objRecvRspFn_Login,
gos_idcmd.Heartbeat : objRecvRspFn_Heartbeat,
gos_idcmd.MakeStage : objRecvRspFn_MakeStage,
gos_idcmd.EnterStage : objRecvRspFn_EnterStage,
gos_idcmd.ChatToStage : objRecvRspFn_ChatToStage,
gos_idcmd.LeaveStage : objRecvRspFn_LeaveStage,

}

	func objRecvRspFn_Invalid(me interface{}, hd gos_packet.Header, body interface{}) error {
		robj , ok := body.(*gos_obj.RspInvalid_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	func objRecvRspFn_Login(me interface{}, hd gos_packet.Header, body interface{}) error {
		robj , ok := body.(*gos_obj.RspLogin_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	func objRecvRspFn_Heartbeat(me interface{}, hd gos_packet.Header, body interface{}) error {
		robj , ok := body.(*gos_obj.RspHeartbeat_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	func objRecvRspFn_MakeStage(me interface{}, hd gos_packet.Header, body interface{}) error {
		robj , ok := body.(*gos_obj.RspMakeStage_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	func objRecvRspFn_EnterStage(me interface{}, hd gos_packet.Header, body interface{}) error {
		robj , ok := body.(*gos_obj.RspEnterStage_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	func objRecvRspFn_ChatToStage(me interface{}, hd gos_packet.Header, body interface{}) error {
		robj , ok := body.(*gos_obj.RspChatToStage_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	func objRecvRspFn_LeaveStage(me interface{}, hd gos_packet.Header, body interface{}) error {
		robj , ok := body.(*gos_obj.RspLeaveStage_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

*/
