// Code generated by "genprotocol -ver=ee0c2a9542c23df14c7723030f3c8ad53da871d9e014d150b2e62d1ce8399fde -basedir=. -prefix=gos -statstype=int"

package gos_handlersp

/* obj base demux fn map template

var DemuxRsp2ObjFnMap = [...]func(me interface{}, hd gos_packet.Header, body interface{}) error {
gos_idcmd.Invalid : objRecvRspFn_Invalid, // Invalid not used, make empty packet error
gos_idcmd.Login : objRecvRspFn_Login, // Login make session with nickname and enter stage
gos_idcmd.Heartbeat : objRecvRspFn_Heartbeat, // Heartbeat prevent connection timeout
gos_idcmd.Chat : objRecvRspFn_Chat, // Chat chat to stage
gos_idcmd.Act : objRecvRspFn_Act, // Act send user action

}

	// Invalid not used, make empty packet error
	func objRecvRspFn_Invalid(me interface{}, hd gos_packet.Header, body interface{}) error {
		robj , ok := body.(*gos_obj.RspInvalid_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	// Login make session with nickname and enter stage
	func objRecvRspFn_Login(me interface{}, hd gos_packet.Header, body interface{}) error {
		robj , ok := body.(*gos_obj.RspLogin_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	// Heartbeat prevent connection timeout
	func objRecvRspFn_Heartbeat(me interface{}, hd gos_packet.Header, body interface{}) error {
		robj , ok := body.(*gos_obj.RspHeartbeat_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	// Chat chat to stage
	func objRecvRspFn_Chat(me interface{}, hd gos_packet.Header, body interface{}) error {
		robj , ok := body.(*gos_obj.RspChat_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	// Act send user action
	func objRecvRspFn_Act(me interface{}, hd gos_packet.Header, body interface{}) error {
		robj , ok := body.(*gos_obj.RspAct_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

*/
