// Code generated by "genprotocol.exe -ver=fa962a76ad7b14946f492eb8876e2f538e89415bc44d01f1655f1ad6b962a045 -basedir=protocol_gos -prefix=gos -statstype=int"

package gos_handlereq

/* obj base demux fn map template
	var DemuxReq2ObjAPIFnMap = [...]func(
		me interface{}, hd gos_packet.Header, robj interface{}) (
		gos_packet.Header, interface{}, error){
	gos_idcmd.Invalid: Req2ObjAPI_Invalid,// Invalid not used, make empty packet error
gos_idcmd.Login: Req2ObjAPI_Login,// Login make session with nickname and enter stage
gos_idcmd.Heartbeat: Req2ObjAPI_Heartbeat,// Heartbeat prevent connection timeout
gos_idcmd.Chat: Req2ObjAPI_Chat,// Chat chat to stage
gos_idcmd.Act: Req2ObjAPI_Act,// Act send user action

}   // DemuxReq2ObjAPIFnMap

	// Invalid not used, make empty packet error
	func Req2ObjAPI_Invalid(
		me interface{}, hd gos_packet.Header, robj interface{}) (
		gos_packet.Header, interface{},  error) {
		req, ok := robj.(*gos_obj.ReqInvalid_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqInvalid(me, hd, req)
		return rhd, rsp, err
	}
	// Invalid not used, make empty packet error
	func objAPIFn_ReqInvalid(
		me interface{}, hd gos_packet.Header, robj *gos_obj.ReqInvalid_data) (
		gos_packet.Header, *gos_obj.RspInvalid_data, error) {
		sendHeader := gos_packet.Header{
			ErrorCode : gos_error.None,
		}
		sendBody := &gos_obj.RspInvalid_data{
		}
		return sendHeader, sendBody, nil
	}

	// Login make session with nickname and enter stage
	func Req2ObjAPI_Login(
		me interface{}, hd gos_packet.Header, robj interface{}) (
		gos_packet.Header, interface{},  error) {
		req, ok := robj.(*gos_obj.ReqLogin_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqLogin(me, hd, req)
		return rhd, rsp, err
	}
	// Login make session with nickname and enter stage
	func objAPIFn_ReqLogin(
		me interface{}, hd gos_packet.Header, robj *gos_obj.ReqLogin_data) (
		gos_packet.Header, *gos_obj.RspLogin_data, error) {
		sendHeader := gos_packet.Header{
			ErrorCode : gos_error.None,
		}
		sendBody := &gos_obj.RspLogin_data{
		}
		return sendHeader, sendBody, nil
	}

	// Heartbeat prevent connection timeout
	func Req2ObjAPI_Heartbeat(
		me interface{}, hd gos_packet.Header, robj interface{}) (
		gos_packet.Header, interface{},  error) {
		req, ok := robj.(*gos_obj.ReqHeartbeat_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqHeartbeat(me, hd, req)
		return rhd, rsp, err
	}
	// Heartbeat prevent connection timeout
	func objAPIFn_ReqHeartbeat(
		me interface{}, hd gos_packet.Header, robj *gos_obj.ReqHeartbeat_data) (
		gos_packet.Header, *gos_obj.RspHeartbeat_data, error) {
		sendHeader := gos_packet.Header{
			ErrorCode : gos_error.None,
		}
		sendBody := &gos_obj.RspHeartbeat_data{
		}
		return sendHeader, sendBody, nil
	}

	// Chat chat to stage
	func Req2ObjAPI_Chat(
		me interface{}, hd gos_packet.Header, robj interface{}) (
		gos_packet.Header, interface{},  error) {
		req, ok := robj.(*gos_obj.ReqChat_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqChat(me, hd, req)
		return rhd, rsp, err
	}
	// Chat chat to stage
	func objAPIFn_ReqChat(
		me interface{}, hd gos_packet.Header, robj *gos_obj.ReqChat_data) (
		gos_packet.Header, *gos_obj.RspChat_data, error) {
		sendHeader := gos_packet.Header{
			ErrorCode : gos_error.None,
		}
		sendBody := &gos_obj.RspChat_data{
		}
		return sendHeader, sendBody, nil
	}

	// Act send user action
	func Req2ObjAPI_Act(
		me interface{}, hd gos_packet.Header, robj interface{}) (
		gos_packet.Header, interface{},  error) {
		req, ok := robj.(*gos_obj.ReqAct_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqAct(me, hd, req)
		return rhd, rsp, err
	}
	// Act send user action
	func objAPIFn_ReqAct(
		me interface{}, hd gos_packet.Header, robj *gos_obj.ReqAct_data) (
		gos_packet.Header, *gos_obj.RspAct_data, error) {
		sendHeader := gos_packet.Header{
			ErrorCode : gos_error.None,
		}
		sendBody := &gos_obj.RspAct_data{
		}
		return sendHeader, sendBody, nil
	}

*/
