// Code generated by "genprotocol -ver=68269c8bfeecd6e461aa862d64007f60a1aeccd64229d523ae7b99a446255112 -basedir=. -prefix=gos -statstype=int"

package gos_version

const ProtocolVersion = "68269c8bfeecd6e461aa862d64007f60a1aeccd64229d523ae7b99a446255112"
