// Code generated by "genprotocol -ver=fa962a76ad7b14946f492eb8876e2f538e89415bc44d01f1655f1ad6b962a045 -basedir=protocol_gos -prefix=gos -statstype=int"

package gos_version

const ProtocolVersion = "fa962a76ad7b14946f492eb8876e2f538e89415bc44d01f1655f1ad6b962a045"
