// Code generated by "genprotocol -ver=ee0c2a9542c23df14c7723030f3c8ad53da871d9e014d150b2e62d1ce8399fde -basedir=. -prefix=gos -statstype=int"

package gos_version

const ProtocolVersion = "ee0c2a9542c23df14c7723030f3c8ad53da871d9e014d150b2e62d1ce8399fde"
