// Code generated by "genprotocol -ver=68269c8bfeecd6e461aa862d64007f60a1aeccd64229d523ae7b99a446255112 -basedir=. -prefix=gos -statstype=int"

package gos_obj

import "github.com/kasworld/goonlinescaffolding/protocol_gos/gos_idcmd"

type ReqInvalid_data struct {
	Dummy uint8
}
type RspInvalid_data struct {
	Dummy uint8
}

type ReqLogin_data struct {
	SessionKey string
	NickName   string
	AuthKey    string
}
type RspLogin_data struct {
	Version         string
	ProtocolVersion string
	DataVersion     string

	SessionKey string
	NickName   string
	CmdList    [gos_idcmd.CommandID_Count]bool
}

type ReqHeartbeat_data struct {
	Tick int64
}
type RspHeartbeat_data struct {
	Tick int64
}

type ReqMakeStage_data struct {
	Dummy uint8
}
type RspMakeStage_data struct {
	Dummy uint8
}

type ReqEnterStage_data struct {
	StageUUID string // may be not same to req stage
	NickToUse string
}
type RspEnterStage_data struct {
	StageUUID string // may be not same to req stage
	NickToUse string // may be not same to req nick
}

type ReqChatToStage_data struct {
	Chat string
}
type RspChatToStage_data struct {
	Dummy uint8
}

type ReqLeaveStage_data struct {
	Dummy uint8
}
type RspLeaveStage_data struct {
	Dummy uint8
}

type NotiInvalid_data struct {
	Dummy uint8
}

type NotiStageInfo_data struct {
	Tick int64
}

type NotiStageChat_data struct {
	SenderNick string
	Chat       string
}
