// Code generated by "genprotocol -ver=fa962a76ad7b14946f492eb8876e2f538e89415bc44d01f1655f1ad6b962a045 -basedir=protocol_gos -prefix=gos -statstype=int"

package gos_obj

/* protocol template

// Invalid not used, make empty packet error
type ReqInvalid_data struct {
	Dummy uint8 // change as you need
}
// Invalid not used, make empty packet error
type RspInvalid_data struct {
	Dummy uint8 // change as you need
}

// Login make session with nickname and enter stage
type ReqLogin_data struct {
	Dummy uint8 // change as you need
}
// Login make session with nickname and enter stage
type RspLogin_data struct {
	Dummy uint8 // change as you need
}

// Heartbeat prevent connection timeout
type ReqHeartbeat_data struct {
	Dummy uint8 // change as you need
}
// Heartbeat prevent connection timeout
type RspHeartbeat_data struct {
	Dummy uint8 // change as you need
}

// Chat chat to stage
type ReqChat_data struct {
	Dummy uint8 // change as you need
}
// Chat chat to stage
type RspChat_data struct {
	Dummy uint8 // change as you need
}

// Act send user action
type ReqAct_data struct {
	Dummy uint8 // change as you need
}
// Act send user action
type RspAct_data struct {
	Dummy uint8 // change as you need
}

// Invalid not used, make empty packet error
type NotiInvalid_data struct {
	Dummy uint8 // change as you need
}

// StageInfo for client display
type NotiStageInfo_data struct {
	Dummy uint8 // change as you need
}

// StageChat broadcasted chat
type NotiStageChat_data struct {
	Dummy uint8 // change as you need
}

*/
