// Code generated by "genprotocol -ver=68269c8bfeecd6e461aa862d64007f60a1aeccd64229d523ae7b99a446255112 -basedir=. -prefix=gos -statstype=int"

package gos_obj

/* protocol template

type ReqInvalid_data struct {
	Dummy uint8
}
type RspInvalid_data struct {
	Dummy uint8
}

type ReqLogin_data struct {
	Dummy uint8
}
type RspLogin_data struct {
	Dummy uint8
}

type ReqHeartbeat_data struct {
	Dummy uint8
}
type RspHeartbeat_data struct {
	Dummy uint8
}

type ReqMakeStage_data struct {
	Dummy uint8
}
type RspMakeStage_data struct {
	Dummy uint8
}

type ReqEnterStage_data struct {
	Dummy uint8
}
type RspEnterStage_data struct {
	Dummy uint8
}

type ReqChatToStage_data struct {
	Dummy uint8
}
type RspChatToStage_data struct {
	Dummy uint8
}

type ReqLeaveStage_data struct {
	Dummy uint8
}
type RspLeaveStage_data struct {
	Dummy uint8
}

type NotiInvalid_data struct {
	Dummy uint8
}

type NotiStageInfo_data struct {
	Dummy uint8
}

type NotiStageChat_data struct {
	Dummy uint8
}

*/
