// Code generated by "genprotocol -ver=ee0c2a9542c23df14c7723030f3c8ad53da871d9e014d150b2e62d1ce8399fde -basedir=. -prefix=gos -statstype=int"

package gos_obj

/* protocol template

// Invalid not used, make empty packet error
type ReqInvalid_data struct {
	Dummy uint8 // change as you need
}
// Invalid not used, make empty packet error
type RspInvalid_data struct {
	Dummy uint8 // change as you need
}

// Login make session with nickname and enter stage
type ReqLogin_data struct {
	Dummy uint8 // change as you need
}
// Login make session with nickname and enter stage
type RspLogin_data struct {
	Dummy uint8 // change as you need
}

// Heartbeat prevent connection timeout
type ReqHeartbeat_data struct {
	Dummy uint8 // change as you need
}
// Heartbeat prevent connection timeout
type RspHeartbeat_data struct {
	Dummy uint8 // change as you need
}

// Chat chat to stage
type ReqChat_data struct {
	Dummy uint8 // change as you need
}
// Chat chat to stage
type RspChat_data struct {
	Dummy uint8 // change as you need
}

// Act send user action
type ReqAct_data struct {
	Dummy uint8 // change as you need
}
// Act send user action
type RspAct_data struct {
	Dummy uint8 // change as you need
}

// Invalid not used, make empty packet error
type NotiInvalid_data struct {
	Dummy uint8 // change as you need
}

// StageInfo for client display
type NotiStageInfo_data struct {
	Dummy uint8 // change as you need
}

// StageChat broadcasted chat
type NotiStageChat_data struct {
	Dummy uint8 // change as you need
}

*/
