// Code generated by "genprotocol -ver=68269c8bfeecd6e461aa862d64007f60a1aeccd64229d523ae7b99a446255112 -basedir=. -prefix=gos -statstype=int"

package gos_handlenoti

/* bytes base demux fn map template

var DemuxNoti2ByteFnMap = [...]func(me interface{}, hd gos_packet.Header, rbody []byte) error {
gos_idnoti.Invalid : bytesRecvNotiFn_Invalid,
gos_idnoti.StageInfo : bytesRecvNotiFn_StageInfo,
gos_idnoti.StageChat : bytesRecvNotiFn_StageChat,

}

	func bytesRecvNotiFn_Invalid(me interface{}, hd gos_packet.Header, rbody []byte) error {
		robj, err := gos_json.UnmarshalPacket(hd, rbody)
		if err != nil {
			return fmt.Errorf("Packet type miss match %v", rbody)
		}
		recved , ok := robj.(*gos_obj.NotiInvalid_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", robj )
		}
		return fmt.Errorf("Not implemented %v", recved)
	}

	func bytesRecvNotiFn_StageInfo(me interface{}, hd gos_packet.Header, rbody []byte) error {
		robj, err := gos_json.UnmarshalPacket(hd, rbody)
		if err != nil {
			return fmt.Errorf("Packet type miss match %v", rbody)
		}
		recved , ok := robj.(*gos_obj.NotiStageInfo_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", robj )
		}
		return fmt.Errorf("Not implemented %v", recved)
	}

	func bytesRecvNotiFn_StageChat(me interface{}, hd gos_packet.Header, rbody []byte) error {
		robj, err := gos_json.UnmarshalPacket(hd, rbody)
		if err != nil {
			return fmt.Errorf("Packet type miss match %v", rbody)
		}
		recved , ok := robj.(*gos_obj.NotiStageChat_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", robj )
		}
		return fmt.Errorf("Not implemented %v", recved)
	}

*/
