// Code generated by "genprotocol -ver=ee0c2a9542c23df14c7723030f3c8ad53da871d9e014d150b2e62d1ce8399fde -basedir=. -prefix=gos -statstype=int"

package gos_handlenoti

/* bytes base demux fn map template

var DemuxNoti2ByteFnMap = [...]func(me interface{}, hd gos_packet.Header, rbody []byte) error {
gos_idnoti.Invalid : bytesRecvNotiFn_Invalid,// Invalid not used, make empty packet error
gos_idnoti.StageInfo : bytesRecvNotiFn_StageInfo,// StageInfo for client display
gos_idnoti.StageChat : bytesRecvNotiFn_StageChat,// StageChat broadcasted chat

}

	// Invalid not used, make empty packet error
	func bytesRecvNotiFn_Invalid(me interface{}, hd gos_packet.Header, rbody []byte) error {
		robj, err := gos_json.UnmarshalPacket(hd, rbody)
		if err != nil {
			return fmt.Errorf("Packet type miss match %v", rbody)
		}
		recved , ok := robj.(*gos_obj.NotiInvalid_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", robj )
		}
		return fmt.Errorf("Not implemented %v", recved)
	}

	// StageInfo for client display
	func bytesRecvNotiFn_StageInfo(me interface{}, hd gos_packet.Header, rbody []byte) error {
		robj, err := gos_json.UnmarshalPacket(hd, rbody)
		if err != nil {
			return fmt.Errorf("Packet type miss match %v", rbody)
		}
		recved , ok := robj.(*gos_obj.NotiStageInfo_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", robj )
		}
		return fmt.Errorf("Not implemented %v", recved)
	}

	// StageChat broadcasted chat
	func bytesRecvNotiFn_StageChat(me interface{}, hd gos_packet.Header, rbody []byte) error {
		robj, err := gos_json.UnmarshalPacket(hd, rbody)
		if err != nil {
			return fmt.Errorf("Packet type miss match %v", rbody)
		}
		recved , ok := robj.(*gos_obj.NotiStageChat_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", robj )
		}
		return fmt.Errorf("Not implemented %v", recved)
	}

*/
