// Code generated by "genprotocol -ver=ee0c2a9542c23df14c7723030f3c8ad53da871d9e014d150b2e62d1ce8399fde -basedir=. -prefix=gos -statstype=int"

package gos_const

/*  copy to no _gen file, and edit it
const (
	// MaxBodyLen set to max body len, affect send/recv buffer size
	MaxBodyLen = 0xfffff
	// PacketBufferPoolSize max size of pool packet buffer
	PacketBufferPoolSize = 100

	// ServerAPICallTimeOutDur api call watchdog timer
	ServerAPICallTimeOutDur = time.Second * 2
)
*/
