// Code generated by "genprotocol -ver=68269c8bfeecd6e461aa862d64007f60a1aeccd64229d523ae7b99a446255112 -basedir=. -prefix=gos -statstype=int"

package gos_idnoti_stats

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/goonlinescaffolding/protocol_gos/gos_idnoti"
)

type NotiIDStat [gos_idnoti.NotiID_Count]int

func (es NotiIDStat) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "NotiIDStats[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			gos_idnoti.NotiID(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *NotiIDStat) Inc(e gos_idnoti.NotiID) {
	es[e] += 1
}
func (es *NotiIDStat) Add(e gos_idnoti.NotiID, v int) {
	es[e] += v
}
func (es *NotiIDStat) SetIfGt(e gos_idnoti.NotiID, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es NotiIDStat) Get(e gos_idnoti.NotiID) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es NotiIDStat) Iter(fn func(i gos_idnoti.NotiID, v int) bool) bool {
	for i, v := range es {
		if fn(gos_idnoti.NotiID(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es NotiIDStat) VectorAdd(arg NotiIDStat) NotiIDStat {
	var rtn NotiIDStat
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es NotiIDStat) VectorSub(arg NotiIDStat) NotiIDStat {
	var rtn NotiIDStat
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es NotiIDStat) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>NotiID statistics</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return gos_idnoti.NotiID(i).String()
}

var IndexFn = template.FuncMap{
	"NotiIDIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{NotiIDIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
